name: plan_ex_app
description: "Plan Execute Next"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  connectivity_plus: ^7.0.0
  fluttertoast: ^9.0.0
  get_storage: ^2.1.1
  provider: ^6.1.5+1
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  google_fonts: ^6.3.2
  firebase_app_check: ^0.4.1+2
  google_sign_in: ^7.2.0
  flutter_svg: ^2.2.2
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3
  file_picker: ^10.3.6
  uuid: ^4.5.2
  firebase_storage: ^13.0.4
  intl: ^0.20.2
  supabase_flutter: ^2.10.3
  flutter_dotenv: ^6.0.0
  url_launcher: ^6.3.2
  sign_in_with_apple: ^7.0.1
  image_picker: ^1.2.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  webview_flutter: ^4.13.0
  open_filex: ^4.7.0
  dio: ^5.9.0
  path_provider: ^2.1.5
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - .env
